### PR TITLE
point to latest version in usage example

### PR DESCRIPTION
**Pull request by yelizariev**
Thanks for the simple useful action!

### CODE REVIEW

**Comment by marocchino** [comment]
In fact, v1 is an alias for the latest version of the v1 family. 😅 

If you want to see the sha number, check out this:
https://github.com/marocchino/sticky-pull-request-comment/tags

**Comment by yelizariev** [comment]
Are you sure, that you can update v1 to always point to the latest version of v1 series?

**Comment by marocchino** [comment]
Yes. I have done it so far. and it is very common. For example, `actions/cache` is one of the official repository and did it.

https://github.com/actions/cache/tags

**Comment by yelizariev** [comment]
Oh, ok. It makes sense then

**Pull request closed without merging**
